"""removed code FK

Revision ID: 59373f853245
Revises: 49cfc8ec36b5
Create Date: 2026-06-07 16:43:39.530123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59373f853245'
down_revision: Union[str, Sequence[str], None] = '49cfc8ec36b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.create_unique_constraint(None, 'urls', ['short_code'])
    op.drop_constraint(op.f('urls_short_code_fkey'), 'urls', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('urls_short_code_fkey'), 'urls', 'codes', ['short_code'], ['code'])
    op.drop_constraint(None, 'urls', type_='unique')
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=False)
    # ### end Alembic commands ###
