"""unique on original_url,client_ip,expires_at

Revision ID: aa8fe67c1897
Revises: eb95886673ba
Create Date: 2026-06-09 16:15:00.676298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8fe67c1897'
down_revision: Union[str, Sequence[str], None] = 'eb95886673ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint('uq_original_url_client_ip_expires_at', 'urls', ['original_url', 'client_ip', 'expires_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_original_url_client_ip_expires_at', 'urls', type_='unique')
    op.alter_column('urls', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
