"""added client_ip column to urls

Revision ID: eb95886673ba
Revises: 11c41c2970b5
Create Date: 2026-06-09 10:49:45.755716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb95886673ba'
down_revision: Union[str, Sequence[str], None] = '11c41c2970b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('client_ip', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'client_ip')
    # ### end Alembic commands ###
