import random
from dataclasses import dataclass
from datetime import datetime

from src.modules.shared.constants import Error

from .interfaces import IUOW, ICodeGenerator
from ..domain.models import ShortURL

# TODO - Later we can read this from .env
FALLBACK_CODE_GENERATION_MAX_RETRIES = 5


@dataclass(frozen=True)
class ShortURLCommand:
    url: str
    expires_at: datetime | None = None


@dataclass(frozen=True)
class VisitLink:
    short_code: str


class URLCommandHandler:
    def __init__(
        self,
        uow: IUOW,
    ):
        self.uow = uow

    async def shorten_url(
        self, code_generator: ICodeGenerator, cmd: ShortURLCommand
    ) -> ShortURL | Error:
        async with self.uow as uow:
            # unused_code pops a code from codes generated by a background job
            unused_code = await uow.codes.pop_unused()
            if unused_code is None:
                # If somehow there is no code in database we have to generate it
                # But this way we may encounter hash collision problem
                # So we have to try again until a unique generate.

                for _ in range(FALLBACK_CODE_GENERATION_MAX_RETRIES):
                    generated_code = code_generator.generate_code(
                        random.randint(1, 62**7)
                    )

                    existed = await uow.urls.get_by_short_code(generated_code)

                    if existed is None:
                        unused_code = generated_code
                        break

                else:
                    return Error.internal_error(
                        message=f"Failed to generate unique code after {FALLBACK_CODE_GENERATION_MAX_RETRIES} attempts"
                    )

            domain_url = ShortURL.create(
                original_url=cmd.url,
                short_code=unused_code,
                expires_at=cmd.expires_at,
            )

            await uow.urls.add(domain_url)
        return domain_url

    async def visit_link(self, cmd: VisitLink) -> str | Error:
        async with self.uow as uow:
            domain_url = await uow.urls.get_by_short_code(cmd.short_code)
            if domain_url is None:
                return Error.not_found(
                    entity="url", field_name="short_code", field_value=cmd.short_code
                )
            original_url = domain_url.resolve()
            domain_url.rgister_click()

        return original_url.value
