from dataclasses import dataclass
from datetime import datetime

from .interfaces import IUOW, ICodeGenerator
from ..domain.models import ShortURL
# from ..domain import value_objects


@dataclass(frozen=True)
class ShortURLCommand:
    url: str
    expires_at: datetime | None = None


class URLCommandHandler:
    def __init__(
        self,
        uow: IUOW,
    ):
        self._uow = uow

    async def shorten_url(
        self, code_generator: ICodeGenerator, command: ShortURLCommand
    ) -> None:
        async with self._uow as uow:
            # unused_code pops a code from codes generated by a background job
            unused_code = await uow.codes.pop_unused()
            if unused_code is None:
                # If somehow there is no code in database we have to generate it
                # But this way we may encounter hash collision problem
                # So we have to try again until a unique generate.

                for _ in range(5):
                    generated_code = code_generator.generate()

                    existing = await uow.urls.get_by_short_code(generated_code)

                    if existing is None:
                        unused_code = generated_code
                        break

                else:
                    raise RuntimeError(
                        "Failed to generate unique code after 5 attempts"
                    )

            domain_url = ShortURL.create(
                original_url=command.url,
                short_code=unused_code,
                expires_at=command.expires_at,
            )

            await uow.urls.add(domain_url)
